# Notebook Information

This notebook is an initial stab at looking at the aquired datasets, seeing what data we have, and seeing how the data can be merged and aligned for future modeling work.

In [1]:
# Standard package imports

# Data anaysis
import pandas as pd
import numpy as np

# Plotting and Correlation Maths
import seaborn as sns
import scipy as sci

# Simple model development
import sklearn as sk

import os

In [3]:
# You will probably be in the /notebooks directory if you've placed you
#  Jupyter notebook in the right spot.
os.getcwd()

'c:\\Users\\btb51\\Documents\\GitHub\\DAAN881_Team1\\opioid_analytics\\notebooks'

# Reading data and looking at some summary statistics

## data-table

This seems to include the State, the Data Reported, and the Years Available.

This may not actually be useful.

In [4]:
dt = pd.read_csv('../data/raw/data-table.csv')
dt.head(5)

,State,Data reported,Years available
0,Alabama,Unfunded State,NaN
1,Alaska,Emergency Department & Inpatient Hospitalization,2018-2022
2,Arizona,Unfunded State,NaN
3,Arkansas,Unfunded State,NaN
4,California,Emergency Department Only,2018-2022

In [5]:
dt.describe()

          State   Data reported Years available
count        50              50              25
unique       50               4               2
top     Alabama  Unfunded State       2018-2022
freq          1              25              24

## County Opioid Dispencing Rates

Data provided by the CDC at:  https://www.cdc.gov/overdose-prevention/data-research/facts-stats/opioid-dispensing-rate-maps.html

In [6]:
count_disp_rates_df = pd.read_csv('../data/raw/County Opioid Dispensing Rates.csv')
count_disp_rates_df.head(5)

,FullGeoName,YEAR,STATE_NAME,STATE_ABBREV,COUNTY_NAME,STATE_COUNTY_FIP_U,opioid_dispensing_rate,Opioid Dispensing Rate (per 100 persons)
0,"AL, Autauga",2019,Alabama,AL,Autauga County,1001,102.8,>51.0
1,"AL, Baldwin",2019,Alabama,AL,Baldwin County,1003,67.9,>51.0
2,"AL, Barbour",2019,Alabama,AL,Barbour County,1005,27.6,18.6 - 32.2
3,"AL, Bibb",2019,Alabama,AL,Bibb County,1007,21.0,18.6 - 32.2
4,"AL, Blount",2019,Alabama,AL,Blount County,1009,23.8,18.6 - 32.2

In [27]:
sum(count_disp_rates_df['COUNTY_NAME'] == 'Allegheny')

0

In [7]:
# What years do we have county data for?
count_disp_rates_df['YEAR'].unique()

array([2019, 2020, 2021, 2022], dtype=int64)

In [8]:
count_disp_rates_df.describe()

               YEAR  STATE_COUNTY_FIP_U  opioid_dispensing_rate
count  12340.000000        12340.000000            12331.000000
mean    2020.498298        30329.250729               38.306496
std        1.118513        15176.674079               30.690663
min     2019.000000         1001.000000                0.000000
25%     2019.000000        18171.000000               18.600000
50%     2020.000000        29147.000000               32.200000
75%     2021.000000        45069.500000               51.000000
max     2022.000000        56045.000000              569.100000

## State Opioid Dispencing Rates

Data provided by the CDC at:  https://www.cdc.gov/overdose-prevention/data-research/facts-stats/opioid-dispensing-rate-maps.html

In [9]:
state_disp_rates_df = pd.read_csv('../data/raw/State Opioid Dispensing Rates.csv')
state_disp_rates_df.head(5)

,YEAR,STATE_NAME,STATE_ABBREV,STATE_FIPS,opioid_dispensing_rate,Opioid Dispensing Rate (per 100 persons)
0,2019,Alabama,AL,1,86.0,>52.8
1,2019,Alaska,AK,2,39.3,36.1 - 42.7
2,2019,Arizona,AZ,4,44.2,42.8 - 52.8
3,2019,Arkansas,AR,5,81.1,>52.8
4,2019,California,CA,6,31.0,<36.1

In [10]:
# What Years do we have state data for?
state_disp_rates_df['YEAR'].unique()

array([2019, 2020, 2021, 2022], dtype=int64)

In [11]:
state_disp_rates_df.describe()

              YEAR  STATE_FIPS  opioid_dispensing_rate
count   204.000000  204.000000              204.000000
mean   2020.500000   28.960784               45.566176
std       1.120784   15.715401               12.663324
min    2019.000000    1.000000               24.300000
25%    2019.750000   16.000000               36.175000
50%    2020.500000   29.000000               42.750000
75%    2021.250000   42.000000               52.825000
max    2022.000000   56.000000               86.000000

## Dose DX Dashbord information

Data provided by the CDC at: https://www.cdc.gov/overdose-prevention/data-research/facts-stats/dose-dashboard-nonfatal-discharge-data.html

Additional information about DOSE can be found at: https://www.cdc.gov/overdose-prevention/data-research/facts-stats/about-dose-system.html

`TODO`
I need to go through and get this sheet by sheet.  The first sheet I've been reading is 'Data Dictionary' which just talks about what the data is.

In [12]:
dose_df = pd.read_excel('../data/raw/dose_dx_dashboard_v6.xlsx')
dose_df
# dose_data = pd.read_excel('../data/raw/dose_dx_dashboard_v6.xlsx', engine='calamine')
# dose_data
# cols = dose_data[0]
# vals = dose_data[1:]

# dose_df = pd.DataFrame(vals, columns=cols)

# dose_df

,Variable,Definition,Variable Values
0,US State Submission Counts,This sheet provides information on the number ...,NaN
1,dataset,Indicator for the data source for that row of ...,Character (ED or HOSP)
2,month,All (annual) or month value ranging from 1-12 ...,Character (1-12 or all) (where 1=January and 1...
3,year,Year of analysis for that row of data.,"Numeric (2018, 2019, 2020, 2021 or 2022)"
4,jurisdiction_count,Count of states reporting ED visits or Inpatie...,Numeric
5,State Counts & Rates,This sheet provides information on the monthly...,NaN
6,state,The two-digit state abbreviation.,"Character (e.g., AK=Alaska, US=overall for par..."
7,month,All (annual) or month value ranging from 1-12 ...,Character (1-12 or all) (where 1=January and 1...
8,year,Year of analysis for that row of data.,"Numeric (2018, 2019, 2020, 2021 or 2022)"
9,time_frame,Time frame (annual or monthly) for that row of...,Character (annual or monthly)
10,dataset,Indicator for the data source for that row of ...,Character (ED or HOSP)
11,count_alldrug,Annual or monthly count of ED visits or inpati...,Character (count value or suppressed)*
12,count_opioid,Annual or monthly count of ED visits or inpati...,Character (count value or suppressed)*
13,count_heroin,Annual or monthly count of ED visits or inpati...,Character (count value or suppressed)*
14,count_stimulant,Annual or monthly count of ED visits or inpati...,Character (count value or suppressed)*
15,population,State population estimates for that row of data.§,Numeric
16,rate_alldrug,Annual or monthly rate of ED visits or inpatie...,Character (rate value or suppressed)*
17,rate_opioid,Annual or monthly rate of ED visits or inpatie...,Character (rate value or suppressed)*
18,rate_heroin,Annual or monthly rate of ED visits or inpatie...,Character (rate value or suppressed)*
19,rate_stimulant,Annual or monthly rate of ED visits or inpatie...,Character (rate value or suppressed)*
20,County Counts & Rates,This sheet provides information on county-leve...,NaN
21,state,The two-digit state abbreviation.,"Character (e.g., AK=Alaska)"
22,county,County name.,Character†
23,fips,Five-character FIPS code for the county within...,"Character (e.g., 12345, 01234)"
24,year,Year of analysis for that row of data.,"Character (2018, 2019, 2020, 2021, 2022 or 201..."
25,dataset,Indicator for the data source for that row of ...,Character (ED)
26,count_alldrug,The number of ED visits for nonfatal all drug ...,Character (count value or suppressed)*
27,population,County population for that row of data.§ Value...,Numeric
28,rate_alldrug,1-year (annual) or 5-year (2018‒2022) rate of ...,Character (rate value or suppressed)*
29,type,Rate type for that row of data; 1 year (annual...,Character (1 year or 5 years)
30,person_years,The sum of the mid-year county-level populatio...,Numeric
31,Overall by Sex & Age,This sheet provides information on the monthly...,NaN
32,state,The two-digit state abbreviation; data on this...,Character (US=overall for participating jurisd...
33,sex,Two sex categories are presented: M = male and...,"Character (M = male, F = female, Missing)"
34,age,"5 age categories are presented: 0-14, 15-24, 2...","Character (0-14, 15-24, 25-34, 35-54, and 55+ ..."
35,month,All (annual) or month value ranging from 1-12 ...,Character (1-12 or all) (where 1=January and 1...
36,year,Year of analysis for that row of data.,"Numeric (2018, 2019, 2020, 2021 or 2022)"
37,time_frame,Time frame (annual or monthly) for that row of...,Character (annual or monthly)
38,dataset,Indicator for the data source for that row of ...,Character (ED or HOSP)
39,population,State population estimates for all states subm...,Character (count or not available)
40,count_alldrug,Annual or monthly count of ED visits or inpati...,Character (count value or suppressed)*
41,count_opioid,Annual or monthly count of ED visits or inpati...,Character (count value or suppressed)*
42,count_heroin,Annual or monthly count of ED visits or inpati...,Character (count value or suppressed)*
43,count_stimulant,Annual or monthly count of ED visits or inpati...,Character (count value or suppressed)*
44,rate_alldrug,Annual or monthly rate of ED visits or inpatie...,"Character (rate value, suppressed, or not avai..."
45,rate_opioid,Annual or monthly rate of ED visits or inpatie...,"Character (rate value, suppressed, or not avai..."
46,rate_heroin,Annual or monthly rate of ED visits or inpatie...,"Character (rate value, suppressed, or not avai..."
47,rate_stimulant,Annual or monthly rate of ED visits or inpatie...,"Character (rate value, suppressed, or not avai..."
48,* Counts are suppressed when based on 1-9 over...,NaN,NaN
49,§ Mid-year annual population denominators were...,NaN,NaN
50,"† Valdez-Cordova Census Area, Alaska was aboli...",NaN,NaN

In [13]:
dose_df.describe()

,Variable,Definition,Variable Values
count,51,48,44
unique,28,35,19
top,year,Year of analysis for that row of data.,Character (count value or suppressed)*
freq,4,4,9

## Weather Events

`TODO` Where did we get this data?

`Question` This dataset seems to be highly detailed to the Western PA region.  We may need to move our analysis from the state of PA, to the Allegheny County (Pittsburgh) region.

In [100]:
# This is about a 4 minute read on my system (BB) if using just pandas
# Using the python-calamine engine in pandas 2.2.*
#  via the python-calamine package (in environment.yaml) speeds this up
#  to just 30 seconds.  I would recommend installing python-calamine.

weather_events_df = pd.read_excel('../data/raw/WeatherEvents_Jan2016-Dec2022.xlsx', engine='calamine')
weather_events_df.head(5)

,EventId,Type,Severity,StartTime(UTC),EndTime(UTC),Precipitation(in),TimeZone,AirportCode,LocationLat,LocationLng,City,County,State,ZipCode
0,W-1,Snow,Light,2016-01-06 23:14:00,2016-01-07 00:34:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
1,W-2,Snow,Light,2016-01-07 04:14:00,2016-01-07 04:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
2,W-3,Snow,Light,2016-01-07 05:54:00,2016-01-07 15:34:00,0.03,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
3,W-4,Snow,Light,2016-01-08 05:34:00,2016-01-08 05:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
4,W-5,Snow,Light,2016-01-08 13:54:00,2016-01-08 15:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0

In [101]:
# This only has 45 of the 50 states
print(f'There are {len(weather_events_df['State'].unique())} out of 50 states.')
weather_events_df['State'].unique()

There are 45 out of 50 states.

array(['CO', 'OK', 'MN', 'LA', 'WI', 'ID', 'MI', 'KS', 'WY', 'MA', 'MO',
       'NM', 'NC', 'SC', 'RI', 'VA', 'CT', 'OR', 'ND', 'CA', 'NY', 'OH',
       'SD', 'AZ', 'NV', 'IA', 'TX', 'GA', 'NE', 'TN', 'AL', 'IL', 'AR',
       'WA', 'IN', 'UT', 'FL', 'WV', 'MS', 'PA', 'ME', 'MD', 'NJ', 'KY',
       'VT'], dtype=object)

In [102]:
weather_events_df.describe()

       Precipitation(in)    LocationLat    LocationLng        ZipCode
count      999999.000000  999999.000000  999999.000000  991683.000000
mean            0.089890      39.453285     -92.545095   52737.512165
std             0.561167       5.132021      13.733891   26410.391978
min             0.000000      24.726300    -123.140800    1201.000000
25%             0.000000      36.010300     -99.321600   31510.000000
50%             0.000000      39.794500     -90.993800   55008.000000
75%             0.050000      43.208000     -82.159100   73703.000000
max           115.600000      48.929000     -68.017900   99362.000000

## Larger Generic Weather Dataset

In [103]:
generic_weather_df = pd.read_excel('../data/raw/Allegheny County 2017-01-01 to 2024-05-01.xlsx', engine='calamine')
generic_weather_df.head(5)

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations
0,Allegheny County,2017-01-01,43.9,31.4,37.1,40.1,29.0,33.2,28.3,71.1,...,8.2,4,NaN,2017-01-01T07:43:20,2017-01-01T17:04:23,0.12,"Snow, Rain, Partially cloudy",Clearing in the afternoon with early morning s...,rain,"KBTP,KAGC,72512464705,KPIT,72520514762,7252009..."
1,Allegheny County,2017-01-02,46.3,37.0,42.6,43.3,33.2,38.4,38.9,87.1,...,1.3,1,NaN,2017-01-02T07:43:25,2017-01-02T17:05:15,0.16,"Rain, Partially cloudy",Partly cloudy throughout the day with a chance...,rain,"KBTP,KAGC,72512464705,KPIT,72520514762,7252009..."
2,Allegheny County,2017-01-03,48.6,42.9,45.1,46.3,37.7,41.6,42.6,91.0,...,0.7,0,NaN,2017-01-03T07:43:27,2017-01-03T17:06:08,0.19,"Rain, Partially cloudy",Partly cloudy throughout the day with rain.,rain,"KBTP,KAGC,72512464705,KPIT,72520514762,7252009..."
3,Allegheny County,2017-01-04,44.3,21.1,33.8,37.4,8.0,23.6,23.4,67.4,...,6.8,4,NaN,2017-01-04T07:43:28,2017-01-04T17:07:02,0.23,"Snow, Rain, Partially cloudy",Partly cloudy throughout the day with rain or ...,rain,"KBTP,KAGC,72512464705,KPIT,72520514762,7252009..."
4,Allegheny County,2017-01-05,22.6,19.0,20.6,20.8,7.0,11.2,11.5,68.4,...,6.0,3,NaN,2017-01-05T07:43:26,2017-01-05T17:07:58,0.25,"Snow, Partially cloudy",Partly cloudy throughout the day with snow.,snow,"KBTP,KAGC,72512464705,KPIT,72520514762,7252009..."

In [104]:
generic_weather_df

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations
0,Allegheny County,2017-01-01,43.9,31.4,37.1,40.1,29.0,33.2,28.3,71.1,...,8.2,4,NaN,2017-01-01T07:43:20,2017-01-01T17:04:23,0.12,"Snow, Rain, Partially cloudy",Clearing in the afternoon with early morning s...,rain,"KBTP,KAGC,72512464705,KPIT,72520514762,7252009..."
1,Allegheny County,2017-01-02,46.3,37.0,42.6,43.3,33.2,38.4,38.9,87.1,...,1.3,1,NaN,2017-01-02T07:43:25,2017-01-02T17:05:15,0.16,"Rain, Partially cloudy",Partly cloudy throughout the day with a chance...,rain,"KBTP,KAGC,72512464705,KPIT,72520514762,7252009..."
2,Allegheny County,2017-01-03,48.6,42.9,45.1,46.3,37.7,41.6,42.6,91.0,...,0.7,0,NaN,2017-01-03T07:43:27,2017-01-03T17:06:08,0.19,"Rain, Partially cloudy",Partly cloudy throughout the day with rain.,rain,"KBTP,KAGC,72512464705,KPIT,72520514762,7252009..."
3,Allegheny County,2017-01-04,44.3,21.1,33.8,37.4,8.0,23.6,23.4,67.4,...,6.8,4,NaN,2017-01-04T07:43:28,2017-01-04T17:07:02,0.23,"Snow, Rain, Partially cloudy",Partly cloudy throughout the day with rain or ...,rain,"KBTP,KAGC,72512464705,KPIT,72520514762,7252009..."
4,Allegheny County,2017-01-05,22.6,19.0,20.6,20.8,7.0,11.2,11.5,68.4,...,6.0,3,NaN,2017-01-05T07:43:26,2017-01-05T17:07:58,0.25,"Snow, Partially cloudy",Partly cloudy throughout the day with snow.,snow,"KBTP,KAGC,72512464705,KPIT,72520514762,7252009..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2673,Allegheny County,2024-04-27,79.1,53.0,65.3,79.1,53.0,65.3,50.3,60.5,...,15.3,7,10.0,2024-04-27T06:23:41,2024-04-27T20:12:13,0.63,"Rain, Partially cloudy",Partly cloudy throughout the day with rain cle...,rain,"KBTP,KAGC,72512464705,KPIT,72520514762,7252009..."
2674,Allegheny County,2024-04-28,82.0,63.2,72.6,81.5,63.2,72.6,55.3,55.6,...,20.8,10,10.0,2024-04-28T06:22:22,2024-04-28T20:13:15,0.67,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"KBTP,KAGC,72512464705,KPIT,72520514762,7252009..."
2675,Allegheny County,2024-04-29,82.9,62.6,74.1,82.1,62.6,73.9,54.6,52.0,...,23.1,9,10.0,2024-04-29T06:21:04,2024-04-29T20:14:17,0.70,Partially cloudy,Becoming cloudy in the afternoon.,partly-cloudy-day,"KBTP,KAGC,72512464705,KPIT,72520514762,7252009..."
2676,Allegheny County,2024-04-30,72.3,61.1,65.9,72.3,61.1,65.9,56.1,71.0,...,11.9,6,10.0,2024-04-30T06:19:47,2024-04-30T20:15:18,0.74,"Rain, Partially cloudy",Partly cloudy throughout the day with afternoo...,rain,"KBTP,KAGC,72512464705,KPIT,72520514762,7252009..."
2677,Allegheny County,2024-05-01,79.9,53.7,67.5,79.9,53.7,67.5,48.6,55.4,...,24.0,8,10.0,2024-05-01T06:18:31,2024-05-01T20:16:20,0.75,Clear,Clear conditions throughout the day.,clear-day,"KBTP,KAGC,72512464705,KPIT,72520514762,7252009..."

In [105]:
generic_weather_df.columns

Index(['name', 'datetime', 'tempmax', 'tempmin', 'temp', 'feelslikemax',
       'feelslikemin', 'feelslike', 'dew', 'humidity', 'precip', 'precipprob',
       'precipcover', 'preciptype', 'snow', 'snowdepth', 'windgust',
       'windspeed', 'winddir', 'sealevelpressure', 'cloudcover', 'visibility',
       'solarradiation', 'solarenergy', 'uvindex', 'severerisk', 'sunrise',
       'sunset', 'moonphase', 'conditions', 'description', 'icon', 'stations'],
      dtype='object')

In [106]:
gen_weather_sel_cols = [
    'name','datetime','tempmax','tempmin','temp','feelslikemax',
    'feelslikemin','feelslike','dew','humidity','precip','precipprob',
    'precipcover','preciptype','snow','snowdepth','windgust','windspeed',
    'winddir','sealevelpressure','cloudcover','visibility','solarradiation','solarenergy',
    'uvindex','severerisk','sunrise','sunset','moonphase'
]

In [107]:
down_sel_generic_weather_df = generic_weather_df[gen_weather_sel_cols]
down_sel_generic_weather_df

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase
0,Allegheny County,2017-01-01,43.9,31.4,37.1,40.1,29.0,33.2,28.3,71.1,...,1021.5,41.7,9.5,95.6,8.2,4,NaN,2017-01-01T07:43:20,2017-01-01T17:04:23,0.12
1,Allegheny County,2017-01-02,46.3,37.0,42.6,43.3,33.2,38.4,38.9,87.1,...,1021.8,87.9,5.5,15.5,1.3,1,NaN,2017-01-02T07:43:25,2017-01-02T17:05:15,0.16
2,Allegheny County,2017-01-03,48.6,42.9,45.1,46.3,37.7,41.6,42.6,91.0,...,1006.3,78.7,5.3,7.9,0.7,0,NaN,2017-01-03T07:43:27,2017-01-03T17:06:08,0.19
3,Allegheny County,2017-01-04,44.3,21.1,33.8,37.4,8.0,23.6,23.4,67.4,...,1007.1,73.0,9.0,78.9,6.8,4,NaN,2017-01-04T07:43:28,2017-01-04T17:07:02,0.23
4,Allegheny County,2017-01-05,22.6,19.0,20.6,20.8,7.0,11.2,11.5,68.4,...,1015.1,83.5,6.4,68.1,6.0,3,NaN,2017-01-05T07:43:26,2017-01-05T17:07:58,0.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2673,Allegheny County,2024-04-27,79.1,53.0,65.3,79.1,53.0,65.3,50.3,60.5,...,1022.5,65.9,9.6,177.0,15.3,7,10.0,2024-04-27T06:23:41,2024-04-27T20:12:13,0.63
2674,Allegheny County,2024-04-28,82.0,63.2,72.6,81.5,63.2,72.6,55.3,55.6,...,1019.8,47.9,9.9,241.0,20.8,10,10.0,2024-04-28T06:22:22,2024-04-28T20:13:15,0.67
2675,Allegheny County,2024-04-29,82.9,62.6,74.1,82.1,62.6,73.9,54.6,52.0,...,1015.8,27.2,9.9,265.8,23.1,9,10.0,2024-04-29T06:21:04,2024-04-29T20:14:17,0.70
2676,Allegheny County,2024-04-30,72.3,61.1,65.9,72.3,61.1,65.9,56.1,71.0,...,1012.7,68.1,9.9,140.0,11.9,6,10.0,2024-04-30T06:19:47,2024-04-30T20:15:18,0.74
2677,Allegheny County,2024-05-01,79.9,53.7,67.5,79.9,53.7,67.5,48.6,55.4,...,1014.5,16.2,9.8,278.9,24.0,8,10.0,2024-05-01T06:18:31,2024-05-01T20:16:20,0.75

In [ ]:
gen_weather_sel_cols

In [117]:
down_sel_generic_weather_df[gen_weather_sel_cols[20:30]].describe()

,cloudcover,visibility,solarradiation,solarenergy,uvindex,severerisk,moonphase
count,2678.000000,2678.000000,2678.000000,2678.000000,2678.000000,843.000000,2678.000000
mean,54.781740,8.912211,125.280358,10.809858,4.795370,14.827995,0.483342
std,29.013607,1.339226,79.305213,6.849332,2.471342,14.298733,0.288079
min,0.000000,1.100000,5.800000,0.500000,0.000000,10.000000,0.000000
25%,29.800000,8.500000,59.050000,5.100000,3.000000,10.000000,0.250000
50%,55.250000,9.500000,110.550000,9.500000,5.000000,10.000000,0.490000
75%,80.475000,9.900000,184.075000,15.900000,7.000000,10.000000,0.747500
max,100.000000,9.900000,345.400000,29.800000,10.000000,100.000000,0.980000

In [111]:
down_sel_generic_weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2678 entries, 0 to 2677
Data columns (total 29 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              2678 non-null   object
 1   datetime          2678 non-null   object
 2   tempmax           2678 non-null   float64
 3   tempmin           2678 non-null   float64
 4   temp              2678 non-null   float64
 5   feelslikemax      2678 non-null   float64
 6   feelslikemin      2678 non-null   float64
 7   feelslike         2678 non-null   float64
 8   dew               2678 non-null   float64
 9   humidity          2678 non-null   float64
 10  precip            2678 non-null   float64
 11  precipprob        2678 non-null   int64
 12  precipcover       2678 non-null   float64
 13  preciptype        1648 non-null   object
 14  snow              2678 non-null   float64
 15  snowdepth         2678 non-null   float64
 16  windgust          2678 non-null   float64
 17  windspeed         2678 non-null   float64
 18  winddir           2678 non-null   float64
 19  sealevelpressure  2678 non-null   float64
 20  cloudcover        2678 non-null   float64
 21  visibility        2678 non-null   float64
 22  solarradiation    2678 non-null   float64
 23  solarenergy       2678 non-null   float64
 24  uvindex           2678 non-null   int64
 25  severerisk        843 non-null    float64
 26  sunrise           2678 non-null   object
 27  sunset            2678 non-null   object
 28  moonphase         2678 non-null   float64
dtypes: float64(22), int64(2), object(5)
memory usage: 606.9+ KB

In [119]:
for col in gen_weather_sel_cols:
    print(f'{col}: {down_sel_generic_weather_df[col].value_counts()}')

name: name
Allegheny County    2678
Name: count, dtype: int64
datetime: datetime
2017-01-01    1
2021-11-15    1
2021-11-17    1
2021-11-18    1
2021-11-19    1
             ..
2019-06-13    1
2019-06-14    1
2019-06-15    1
2019-06-16    1
2024-05-01    1
Name: count, Length: 2678, dtype: int64
tempmax: tempmax
78.4    17
73.9    14
76.6    14
57.8    13
82.4    12
        ..
26.3     1
19.0     1
19.8     1
59.6     1
72.3     1
Name: count, Length: 666, dtype: int64
tempmin: tempmin
64.9    17
66.8    17
30.8    16
38.9    13
28.1    13
        ..
74.2     1
72.6     1
13.0     1
70.2     1
17.1     1
Name: count, Length: 633, dtype: int64
temp: temp
70.1    13
65.7    13
71.2    13
73.2    12
71.1    11
        ..
7.9      1
22.6     1
22.8     1
5.7      1
61.6     1
Name: count, Length: 642, dtype: int64
feelslikemax: feelslikemax
78.4     17
73.9     14
76.6     14
57.8     13
76.9     12
         ..
100.1     1
98.5      1
82.8      1
89.6      1
72.3      1
Name: count, Length: 756, dtype: int64
feelslikemin: feelslikemin
66.8    17
64.9    17
22.8    12
62.6    12
62.1    12
        ..
46.6     1
60.6     1
15.3     1
57.9     1
38.7     1
Name: count, Length: 718, dtype: int64
feelslike: feelslike
71.3    15
65.7    13
73.6    13
64.6    12
60.2    12
        ..
3.5      1
1.1      1
0.6      1
46.1     1
53.8     1
Name: count, Length: 743, dtype: int64
dew: dew
 65.0    13
 60.6    12
 32.1    10
 37.4    10
 66.4    10
         ..
 21.3     1
 7.2      1
-10.8     1
-7.1      1
 32.2     1
Name: count, Length: 654, dtype: int64
humidity: humidity
66.2    16
77.6    16
72.0    15
73.2    14
66.7    13
        ..
92.1     1
41.8     1
29.0     1
90.9     1
40.7     1
Name: count, Length: 590, dtype: int64
precip: precip
0.000    1224
0.001      66
0.008      34
0.003      33
0.002      32
         ...
1.934       1
0.254       1
0.881       1
0.106       1
1.526       1
Name: count, Length: 557, dtype: int64
precipprob: precipprob
100    1454
0      1224
Name: count, dtype: int64
precipcover: precipcover
0.00      1224
4.17       198
8.33       151
12.50      137
16.67      133
20.83      117
25.00      115
29.17       93
37.50       71
41.67       70
33.33       67
45.83       52
50.00       42
54.17       36
62.50       28
58.33       24
66.67       21
70.83       20
75.00       17
83.33       12
79.17       11
91.67       11
87.50       10
100.00      10
95.83        8
Name: count, dtype: int64
preciptype: preciptype
rain                      1223
rain,snow                  290
snow                       112
freezingrain                10
rain,freezingrain            5
freezingrain,snow            3
rain,snow,ice                2
rain,freezingrain,snow       2
freezingrain,snow,ice        1
Name: count, dtype: int64
snow: snow
0.0    2459
0.1      56
0.2      51
0.3      19
0.4      14
0.6      13
0.5      12
0.7       6
0.8       6
1.0       5
0.9       5
1.1       5
1.5       4
1.2       4
1.4       3
1.6       3
1.3       3
2.9       2
1.9       2
2.7       2
4.1       1
2.2       1
2.4       1
2.1       1
Name: count, dtype: int64
snowdepth: snowdepth
0.0    2267
0.1     150
0.2      79
0.3      42
0.4      40
0.5      23
0.6      20
0.7      14
0.8      10
0.9       6
1.5       6
1.4       5
1.3       4
1.1       4
1.6       3
1.0       2
2.4       1
1.2       1
1.9       1
Name: count, dtype: int64
windgust: windgust
20.8    96
21.9    91
18.3    88
19.7    78
23.0    75
        ..
48.8     1
30.7     1
45.2     1
45.3     1
47.9     1
Name: count, Length: 341, dtype: int64
windspeed: windspeed
9.9     41
8.1     36
8.3     35
11.9    34
9.0     32
        ..
22.1     1
25.1     1
25.6     1
23.0     1
20.4     1
Name: count, Length: 229, dtype: int64
winddir: winddir
244.1    7
220.5    6
183.5    6
204.0    5
249.4    5
        ..
116.5    1
69.0     1
48.9     1
150.1    1
262.8    1
Name: count, Length: 1783, dtype: int64
sealevelpressure: sealevelpressure
1017.9    27
1015.0    24
1017.1    23
1014.5    22
1018.9    22
          ..
1035.1     1
1000.3     1
1002.4     1
1036.0     1
996.7      1
Name: count, Length: 349, dtype: int64
cloudcover: cloudcover
100.0    74
99.9     15
99.7     15
99.8     12
99.1     12
         ..
12.6      1
14.2      1
90.0      1
34.2      1
66.2      1
Name: count, Length: 911, dtype: int64
visibility: visibility
9.9    718
9.8    227
9.7    155
9.6    127
9.5    123
      ...
1.1      1
5.2      1
1.9      1
2.2      1
1.2      1
Name: count, Length: 77, dtype: int64
solarradiation: solarradiation
105.3    6
44.5     6
75.5     6
77.3     6
14.0     6
        ..
56.0     1
129.7    1
101.1    1
127.7    1
278.9    1
Name: count, Length: 1689, dtype: int64
solarenergy: solarenergy
2.0     24
3.9     24
6.5     23
8.2     22
6.8     22
        ..
27.0     1
27.4     1
25.1     1
0.5      1
25.8     1
Name: count, Length: 278, dtype: int64
uvindex: uvindex
4     386
5     340
6     307
1     302
7     290
3     289
8     287
2     274
9     167
10     21
0      15
Name: count, dtype: int64
severerisk: severerisk
10.0     725
30.0      75
60.0      25
75.0      12
100.0      6
Name: count, dtype: int64
sunrise: sunrise
2017-01-01T07:43:20    1
2021-11-15T07:06:34    1
2021-11-17T07:08:53    1
2021-11-18T07:10:03    1
2021-11-19T07:11:12    1
                      ..
2019-06-13T05:49:16    1
2019-06-14T05:49:14    1
2019-06-15T05:49:15    1
2019-06-16T05:49:17    1
2024-05-01T06:18:31    1
Name: count, Length: 2678, dtype: int64
sunset: sunset
2017-01-01T17:04:23    1
2021-11-15T17:02:24    1
2021-11-17T17:00:52    1
2021-11-18T17:00:08    1
2021-11-19T16:59:27    1
                      ..
2019-06-13T20:51:04    1
2019-06-14T20:51:30    1
2019-06-15T20:51:54    1
2019-06-16T20:52:16    1
2024-05-01T20:16:20    1
Name: count, Length: 2678, dtype: int64
moonphase: moonphase
0.25    105
0.75     99
0.50     91
0.00     90
0.03     35
       ...
0.77     12
0.74     11
0.24     11
0.76     10
0.26      9
Name: count, Length: 96, dtype: int64

In [120]:
for col in gen_weather_sel_cols:
    print(f'{col}: {down_sel_generic_weather_df[col].unique()}')

name: ['Allegheny County']
datetime: ['2017-01-01' '2017-01-02' '2017-01-03' ... '2024-04-29' '2024-04-30'
 '2024-05-01']
tempmax: [43.9 46.3 48.6 44.3 22.6 17.6 16.  15.7 27.9 49.  54.7 64.4 36.6 35.6
 34.1 38.7 60.2 51.3 41.7 55.8 63.2 60.8 49.9 39.1 51.9 50.3 31.9 33.
 31.6 37.9 24.9 29.9 44.8 54.4 63.4 55.9 29.6 32.9 54.5 55.7 38.8 48.7
 42.  28.4 52.8 65.9 59.5 65.5 65.1 67.9 75.7 65.6 45.4 56.7 61.1 39.8
 30.3 46.2 56.  57.  33.7 25.9 27.7 39.4 35.3 35.2 41.  43.3 39.5 51.
 59.3 41.9 49.5 73.4 72.7 65.4 68.1 59.7 60.1 55.6 52.9 48.  57.1 70.3
 63.1 70.6 64.2 38.2 57.7 71.9 78.4 70.  65.2 71.4 80.8 74.6 67.5 70.1
 75.4 68.5 53.9 66.5 61.  63.6 76.4 80.9 70.4 73.9 85.2 80.6 61.2 58.1
 64.7 71.1 47.8 63.9 70.8 58.6 66.2 68.7 69.9 82.3 86.1 84.5 70.9 74.7
 65.3 71.3 66.8 66.6 77.3 78.  74.9 73.1 74.8 78.9 79.8 73.7 64.  69.8
 76.1 82.4 84.6 86.3 88.7 83.2 84.3 81.2 85.5 87.2 77.6 83.3 75.5 74.3
 73.  74.  84.1 83.1 81.  83.  80.7 77.4 79.5 81.8 87.  76.7 77.8 80.3
 83.9 86.4 77.1 79.4 78.8 79.7 81.4 78.1 82.8 82.5 71.5 74.4 76.5 76.9
 83.8 82.1 84.2 72.1 73.3 77.2 74.5 60.7 65.  80.1 73.6 68.3 64.1 67.4
 68.9 78.2 68.8 72.2 79.  82.  85.1 85.9 88.3 85.4 87.1 89.2 62.  74.2
 70.7 75.8 56.9 69.4 65.8 58.9 45.8 51.6 42.2 47.1 45.6 48.1 62.7 59.
 52.  42.4 37.4 46.7 43.7 44.6 47.6 47.  58.8 42.8 48.5 38.9 52.3 44.7
 55.  61.5 46.9 53.8 42.3 36.2 26.9 34.5 30.8 37.5 39.3 22.8 31.3 26.8
 40.9 39.7 42.9 51.8 40.8 52.2 37.1 32.5 18.8 15.1 13.2 17.9 17.3 12.8
 10.5 12.4 22.4 16.6  8.2 10.8 26.2 33.4 35.8 46.5 23.8 15.3 14.4 25.5
 38.1 62.8 55.1 34.9 28.6 47.2 41.5 44.2 25.2 29.8 38.  28.1 30.6 23.6
 39.9 49.3 34.3 51.1 60.9 33.1 62.6 76.6 57.8 41.2 44.4 39.6 31.1 29.3
 40.  40.5 41.3 34.  29.1 41.1 35.4 31.4 49.1 48.4 50.2 58.5 43.6 37.6
 38.4 33.6 75.1 82.9 57.6 56.8 60.4 50.5 78.6 75.2 64.3 82.2 73.5 81.6
 74.1 77.7 72.5 88.5 59.9 77.9 79.2 89.3 79.6 75.3 72.8 76.8 78.3 79.9
 88.1 90.3 88.4 92.  83.7 85.6 87.3 88.2 78.7 85.7 87.9 80.4 78.5 88.8
 89.7 89.8 91.8 91.7 67.1 67.3 81.7 86.  66.9 67.7 71.6 62.5 63.  67.6
 53.  63.5 51.2 49.6 54.8 56.6 47.5 45.5 49.4 46.1 61.7 51.4 44.1 35.7
 43.5 49.8 39.2 37.3 26.6 45.1 46.6 52.4 50.7 26.1 30.5 42.1 50.4 30.2
 30.7 31.  33.8 46.8 50.9 40.4 45.7 47.9 42.7 34.8 33.3 40.6 42.5 23.9
 28.2 37.  36.4 11.4 25.1 24.2 32.1 41.4 14.7  9.7 18.6 26.3 35.1 46.4
 34.6 30.  46.  53.5 35.  24.7 19.  19.8 29.7 36.3 66.4 55.5 47.4 60.
 56.5 53.6 67.2 51.7 61.6 76.3 70.5 73.2 81.3 84.8 59.6 76.  70.2 71.2
 80.  86.7 89.  88.6 87.4 77.  86.6 89.4 75.6 86.5 79.1 83.6 83.4 81.5
 84.4 79.3 75.  77.5 86.8 82.6 87.8 68.  61.3 66.7 54.9 63.7 71.7 56.3
 55.4 61.8 53.7 36.8 41.6 43.1 52.1 38.3 45.  40.1 27.5 61.9 57.2 57.3
 38.6 41.8 54.3 28.5 26.5 24.  32.4 53.2 35.9 32.7 32.  36.7 34.7 50.1
 65.7 48.3 44.  42.6 69.1 57.5 56.2 56.1 52.5 47.7 58.3 69.3 62.3 50.6
 69.7 84.7 69.  83.5 81.9 80.2 89.5 90.6 92.3 93.7 92.7 91.1 91.2 90.9
 92.1 85.  87.5 88.  84.  85.8 67.  62.4 58.4 72.9 53.3 60.3 55.3 44.9
 71.  50.8 53.4 36.  39.  32.2 43.4 33.9 34.4 25.8 30.4 27.4 28.8 29.4
 28.9 32.8 24.8 28.7 22.7 62.1 36.5 64.6 59.8 64.8 55.2 63.8 72.  53.1
 64.9 69.2 62.9 57.4 69.6 90.4 82.7 85.3 90.2 84.9 73.8 68.4 37.7 38.5
 52.6 45.2 28.3 20.  22.9 19.5 17.1 31.5 18.9 23.7 25.6 21.5 47.3 37.2
 58.7 48.8 60.5 25.4 68.2 66.3 59.1 75.9 91.  87.7 59.2 62.2 59.4 66.
 67.8 31.8 54.1 45.3 40.7 40.3 40.2 12.2 20.6 37.8 33.2 43.2 66.1 89.6
 71.8 90.  80.5 89.1 76.2 81.1 72.4 56.4 52.7 54.6 36.9 19.7 19.2 27.
 24.3 43.8 27.8 58.  50.  44.5 57.9 72.3]
tempmin: [31.4 37.  42.9 21.1 19.   6.6  7.6  7.1  4.9 23.9 39.7 38.5 28.6 26.8
 24.6 25.7 38.4 38.  34.4 43.5 48.3 33.8 35.3 33.2 28.1 27.7 21.7 22.1
 33.1 24.3 13.8 24.7 28.7 30.5 17.3 14.  34.3 35.8 26.7 26.  22.5 20.8
 44.1 44.2 39.2 47.3 52.9 53.6 56.4 29.  26.1 32.9 37.4 43.9 27.2 21.4
 18.5 16.2 37.3 42.4 38.2 36.4 15.1 16.1 18.9 14.4 20.9 21.2 32.4 33.4
 34.5 44.5 25.9 19.3 62.  52.4 52.2 47.5 44.8 48.5 38.9 33.3 54.3 45.
 37.1 32.3 35.6 57.4 57.5 42.1 48.2 51.5 62.8 46.6 56.7 58.2 51.6 42.7
 38.8 46.8 49.1 52.  58.  50.  54.2 58.4 60.4 48.8 45.7 48.7 41.3 41.2
 47.6 49.9 50.1 42.3 45.8 64.3 68.4 64.  59.2 57.8 49.3 57.7 55.4 56.8
 55.7 57.  60.2 61.5 56.3 54.1 54.5 59.9 53.9 51.8 51.2 54.  63.1 66.2
 69.1 67.  68.6 62.9 70.3 58.9 62.3 64.4 67.9 65.6 61.2 55.3 54.7 49.8
 59.7 66.1 73.  67.5 65.1 67.7 56.2 65.  71.3 65.8 61.8 66.7 69.7 70.9
 70.4 72.  68.1 59.3 64.7 64.9 55.9 60.1 63.6 65.7 65.4 66.4 59.5 61.
 60.8 60.5 64.6 62.4 64.8 63.2 53.3 57.1 60.9 60.6 59.1 53.8 61.4 55.1
 49.6 47.7 55.2 57.2 61.6 63.5 62.1 62.2 61.7 62.6 67.4 56.1 49.  41.4
 43.7 53.1 63.8 63.3 66.8 68.  65.3 56.6 44.6 35.2 41.9 50.8 50.4 45.6
 40.6 36.7 38.7 35.1 33.5 48.4 44.  52.3 31.  30.8 17.2 35.9 29.7 32.1
 32.  29.3 23.6 28.9 35.4 37.9 40.  33.  28.8 26.5 21.5 27.1 30.4 13.6
 13.  19.2 16.3 29.4 26.6 39.1 29.2 18.2 13.1  6.1  1.  10.6  8.3  2.2
  1.6  5.4  1.3  3.8 -1.7 -1.  -4.2 27.6 28.  24.1 41.5 25.6  9.2  2.5
  8.1  9.7  2.3  5.8 20.4 39.  26.2 23.2 21.3 36.8 35.  12.3  9.8 11.2
 10.  31.2 15.2 17.5 15.7 37.8 52.5 28.3 24.8 32.2 33.6 59.4 37.5 40.1
 45.2 29.9 40.4 34.  29.1 24.9 20.3 23.  24.4 19.8 25.5 21.8 19.9 23.5
 30.3 27.3 22.  26.9 30.1 26.3 33.7 47.1 30.2 30.  43.  55.6 52.1 52.6
 52.8 61.1 61.9 64.2 57.3 69.8 63.7 46.9 47.9 63.  67.2 72.1 72.4 66.9
 65.2 58.3 68.9 69.3 71.6 70.  56.9 68.8 60.7 72.9 68.3 59.8 65.9 70.1
 68.7 61.3 64.1 67.6 69.2 66.  68.5 69.9 70.8 71.4 67.1 56.  53.2 51.4
 53.7 45.9 39.8 40.5 47.4 34.6 31.6 30.6 42.8 36.5 40.9 40.7 41.8 38.3
 32.6 27.  34.7 36.6 20.7 24.2 32.7 25.8 35.7 45.4 19.4 19.5 18.8 28.4
 23.3 29.5 29.8 20.1 20.  31.3  7.5  1.4  3.  25.1 13.3 16.7  9.4 -4.4
 -5.1  6.5  8.9 42.  47.  15.3 25.3 13.9 22.7 22.9 22.3 30.7 26.4 14.7
  6.7 10.1 25.2 28.2 42.2 50.7 41.6 42.6 44.9 45.1 37.2 52.7 51.7 51.
 45.3 48.6 63.9 59.  65.5 49.4 55.8 66.6 54.6 55.5 69.6 67.8 69.5 69.4
 70.6 72.5 75.5 71.5 66.3 62.7 54.8 56.5 54.4 49.2 60.3 62.5 42.5 55.
 51.9 43.6 37.6 46.5 34.9 43.1 37.7 40.2 17.4 24.  31.8 28.5 32.5 39.3
 31.9 25.  17.9 33.9 29.6 16.6 10.8 19.1 38.6 27.5 36.3 23.8 15.9 15.
 16.5 12.1 32.8 27.9 10.3 18.7 12.4 21.6 21.  39.4 58.8 36.  38.1 34.1
 36.9 47.8 40.8 46.4 57.9 66.5 50.3 71.9 58.7 51.3 60.  58.5 73.1 74.2
 72.6 68.2 70.2 64.5 63.4 58.6 50.5 43.4 39.6 46.3 47.2 46.7 58.1 31.1
 46.1 46.2 45.5 48.1 27.8 12.8 23.7 17.8 11.3 22.6 15.4  9.9 41.1 31.5
 40.3 20.5 48.  43.2 43.3 39.5 71.  49.5 73.6 69.  70.5 71.2 71.7 53.5
 51.1 59.6 44.3 44.7 50.2 23.4 18.  14.9 17.6 14.6 12.7  9.5  1.7 -0.2
  2.8 10.2 11.7 22.2 20.6 12.2 17.7 31.7 10.7 16.8 53.4 41.7 53.  57.6
 74.4 48.9 70.7 43.8 44.4 39.9 34.8 27.4 35.5 -5.  -3.1  8.2 19.7 14.1
 18.1  5.7 24.5 22.4 36.2 49.7 54.9 75.3 73.9 67.3 46.  18.4 23.1 11.5
  7.7 10.9 17.1]
temp: [37.1 42.6 45.1 33.8 20.6 12.3 11.1 10.6 17.  35.8 48.  57.3 32.7 31.3
 30.1 50.1 41.8 37.9 45.6 53.8 54.6 42.9 37.3 44.  38.2 29.9 29.5 25.
 33.1 35.7 30.6 22.  22.6 36.6 41.  54.2 43.3 22.4 21.1 46.5 46.8 33.
 37.4 25.5 36.5 54.1 52.6 49.2 55.5 58.5 60.4 65.6 47.9 31.2 39.2 48.4
 55.6 32.8 25.8 24.7 47.  53.4 47.3 48.2 29.2 20.5 22.1 28.6 26.  19.5
 27.4 36.7 36.4 42.5 50.2 32.  33.5 56.  66.7 58.7 59.5 50.3 49.4 50.8
 40.9 45.5 57.9 59.6 55.7 51.4 34.8 44.2 55.  68.1 63.7 55.9 51.6 60.
 66.3 67.3 60.7 64.5 62.4 48.7 53.6 55.4 63.5 68.5 61.  63.  71.8 69.9
 54.3 54.9 57.7 44.6 47.4 47.2 51.2 59.3 53.3 52.2 59.  57.  75.9 75.3
 72.9 62.9 60.8 60.2 62.  69.6 63.6 63.8 66.  69.4 67.1 66.5 59.2 57.8
 65.8 72.3 75.5 78.2 76.6 73.1 73.8 71.6 74.9 76.4 70.9 74.6 71.3 67.8
 64.6 61.7 64.1 75.4 76.  75.6 73.5 74.8 75.7 72.6 71.2 69.3 68.4 67.5
 71.9 76.3 76.5 72.2 77.2 79.9 78.1 74.  71.  67.  70.  73.3 65.3 74.5
 73.9 74.3 65.7 67.6 68.6 70.1 68.3 69.2 70.5 70.2 75.  69.  64.  61.9
 66.6 66.8 67.4 56.4 63.1 68.9 68.  56.2 58.3 57.4 59.9 62.2 70.8 71.7
 71.4 73.4 73.2 76.9 76.2 63.3 66.2 63.9 65.  66.9 51.7 57.6 60.1 52.9
 49.6 39.1 39.4 40.  58.6 48.6 59.4 50.9 39.6 28.8 26.9 37.5 39.7 41.6
 37.2 34.7 35.9 49.  38.9 41.9 50.  46.  39.5 36.2 40.5 45.  35.  27.6
 29.1 33.3 27.  18.4 32.9 36.  46.1 36.9 49.5 42.7 16.1 10.8  7.6 14.3
 15.1  6.8  5.7  7.9 12.   2.9  3.5 10.1 32.2 32.5 35.3 15.   9.2 17.2
 21.8 15.7 28.7 43.9 53.1 43.6 29.3 36.8 45.2 41.2 18.5 40.2 15.5 19.7
 34.2 19.6 24.6 25.9 19.9 27.9 41.5 42.1 29.6 45.8 49.8 39.3 52.  30.7
 34.1 26.7 30.5 28.5 28.9 33.6 39.  41.4 57.2 38.6 41.3 46.3 42.3 34.5
 30.9 31.  60.6 72.  40.1 32.1 40.7 38.3 44.8 55.2 51.5 51.3 63.4 74.2
 60.5 65.4 71.1 65.9 68.7 68.2 64.4 72.7 77.8 76.1 61.3 53.9 61.8 68.8
 70.4 77.5 81.3 77.1 69.8 69.7 78.6 80.4 79.  79.3 80.9 67.2 77.3 78.9
 77.9 77.7 75.8 69.5 73.  70.7 70.6 78.4 72.5 73.6 80.6 79.2 73.7 78.
 81.2 81.6 61.4 55.8 71.5 60.3 67.9 59.7 74.4 66.1 48.5 43.2 47.5 43.8
 46.4 48.8 37.7 38.5 43.4 44.7 47.1 42.2 54.5 45.9 35.1 29.  31.1 31.7
 33.9 31.6 23.5 27.5 24.5 26.5 36.1 39.8 31.5 26.3 22.5 24.2 22.9 42.8
 45.7 40.3 42.  31.9 27.7 35.6 51.9 34.4 37.6 34.3 21.6 24.9 26.8 27.2
 26.4 28.   6.4 18.  24.8  3.8  2.1 11.3 24.  49.3 49.9 20.1 23.9 35.5
 26.1 28.2 40.6 43.5 33.7 13.2 14.9 23.7 60.9 52.7 34.9 32.4 47.6 49.7
 54.4 59.1 50.7 65.1 64.7 62.8 49.1 52.8 56.1 57.1 64.3 53.5 56.7 69.1
 74.1 75.1 72.8 79.4 82.2 80.3 72.4 70.3 77.6 64.9 64.8 64.2 72.1 76.8
 58.8 53.  52.4 58.1 53.7 54.  58.9 45.3 41.1 20.3 32.3 34.  38.  37.
 38.4 31.4 18.8 33.4 51.1 48.9 41.7 29.4 61.5 45.4 42.4 25.2 23.4 20.
 32.6 30.4 33.2 23.1 22.8 44.3 34.6 38.1 44.9 55.3 54.7 48.3 52.1 52.3
 48.1 43.7 62.6 62.7 56.3 77.  80.2 61.1 77.4 80.  82.  78.5 79.1 83.3
 80.1 79.5 75.2 67.7 58.4 62.1 56.8 56.5 55.1 62.5 58.  51.  47.8 38.8
 56.9 40.8 30.  36.3 30.8 35.4 17.6 17.1 29.8 29.7 21.  21.4 20.2 27.8
 24.1 25.4 17.9 25.7 21.7 44.5 46.9 28.4 37.8 52.5 30.2 76.7 50.4 78.7
 81.1 82.6 74.7 63.2 66.4 65.2 59.8 61.2 43.  40.4 46.2 46.7 20.7 17.4
 26.6 13.3 13.4 16.9 12.1 14.8 16.4 25.6 23.2 44.4 53.2 23.3 44.1 78.3
 65.5 81.5 78.8 62.3 51.8 46.6 47.7 50.6 50.5 24.3 11.6 12.4 25.3 31.8
 16.5 19.  30.3 39.9 80.8 79.7 57.5 43.1 35.2 16.3 13.6 61.6]
feelslikemax: [ 4.010e+01  4.330e+01  4.630e+01  3.740e+01  2.080e+01  9.000e+00
  6.900e+00  3.300e+00  1.960e+01  4.300e+01  5.470e+01  6.440e+01
  3.250e+01  3.560e+01  3.410e+01  3.870e+01  6.020e+01  5.130e+01
  3.900e+01  5.580e+01  6.320e+01  6.080e+01  4.660e+01  3.440e+01
  5.190e+01  5.030e+01  2.180e+01  2.550e+01  2.530e+01  2.370e+01
  3.020e+01  3.080e+01  2.650e+01  1.750e+01  2.260e+01  3.910e+01
  5.440e+01  6.340e+01  5.590e+01  2.030e+01  2.470e+01  5.450e+01
  5.570e+01  3.200e+01  3.570e+01  2.500e+01  5.280e+01  6.590e+01
  5.950e+01  6.550e+01  6.510e+01  6.790e+01  7.570e+01  6.560e+01
  3.270e+01  4.140e+01  5.670e+01  6.110e+01  3.040e+01  2.290e+01
  2.520e+01  4.220e+01  5.600e+01  5.700e+01  3.310e+01  1.610e+01
  2.190e+01  3.350e+01  3.530e+01  1.160e+01  2.880e+01  3.490e+01
  3.850e+01  3.540e+01  5.100e+01  5.930e+01  3.430e+01  4.710e+01
  7.340e+01  7.270e+01  6.540e+01  6.810e+01  5.970e+01  6.010e+01
  5.560e+01  5.290e+01  4.270e+01  5.710e+01  7.030e+01  6.310e+01
  7.060e+01  6.420e+01  3.100e+01  5.770e+01  7.190e+01  7.840e+01
  7.000e+01  6.520e+01  7.140e+01  7.960e+01  7.460e+01  6.750e+01
  7.010e+01  7.540e+01  6.850e+01  5.390e+01  6.650e+01  6.100e+01
  6.360e+01  7.640e+01  8.010e+01  7.040e+01  7.390e+01  8.420e+01
  8.090e+01  6.120e+01  5.810e+01  6.470e+01  7.110e+01  4.400e+01
  6.390e+01  7.080e+01  5.860e+01  6.620e+01  6.870e+01  6.990e+01
  8.160e+01  8.450e+01  8.410e+01  8.180e+01  7.090e+01  7.470e+01
  6.530e+01  7.130e+01  6.680e+01  6.660e+01  7.730e+01  7.800e+01
  7.490e+01  7.310e+01  7.480e+01  7.890e+01  7.980e+01  7.370e+01
  6.400e+01  6.980e+01  7.610e+01  8.230e+01  8.400e+01  8.670e+01
  9.160e+01  8.580e+01  8.810e+01  8.720e+01  8.880e+01  7.760e+01
  8.730e+01  7.550e+01  7.430e+01  7.300e+01  7.400e+01  8.460e+01
  8.210e+01  8.300e+01  8.340e+01  8.750e+01  8.310e+01  8.240e+01
  7.740e+01  7.950e+01  8.560e+01  8.850e+01  7.670e+01  8.470e+01
  7.780e+01  8.100e+01  8.590e+01  8.910e+01  9.170e+01  8.980e+01
  9.100e+01  7.710e+01  7.940e+01  7.880e+01  7.970e+01  7.810e+01
  8.290e+01  8.320e+01  8.430e+01  7.150e+01  7.440e+01  7.650e+01
  7.690e+01  8.570e+01  8.350e+01  8.950e+01  8.440e+01  8.220e+01
  8.190e+01  8.680e+01  7.210e+01  7.330e+01  7.720e+01  7.450e+01
  6.070e+01  6.500e+01  7.360e+01  6.830e+01  6.410e+01  6.740e+01
  6.890e+01  7.820e+01  6.880e+01  7.220e+01  7.900e+01  8.130e+01
  8.360e+01  8.370e+01  8.800e+01  8.760e+01  8.780e+01  6.200e+01
  7.420e+01  7.070e+01  8.170e+01  7.580e+01  5.690e+01  6.940e+01
  6.580e+01  5.890e+01  4.190e+01  5.160e+01  3.650e+01  3.980e+01
  4.810e+01  6.270e+01  5.900e+01  3.660e+01  4.790e+01  5.200e+01
  4.540e+01  3.950e+01  4.440e+01  4.110e+01  5.880e+01  3.590e+01
  4.500e+01  3.800e+01  5.230e+01  4.040e+01  5.500e+01  6.150e+01
  4.690e+01  4.350e+01  5.380e+01  3.480e+01  2.770e+01  2.000e+01
  2.940e+01  2.280e+01  3.300e+01  1.580e+01  2.350e+01  3.580e+01
  3.670e+01  3.790e+01  5.180e+01  3.690e+01  3.840e+01  5.220e+01
  3.110e+01  2.200e+01  8.000e+00  4.700e+00  1.320e+01  1.700e+01
  1.110e+01  1.170e+01 -3.000e+00 -8.000e-01  7.700e+00 -8.600e+00
 -3.500e+00  1.810e+01  2.540e+01  3.470e+01  4.360e+01  1.090e+01
  1.460e+01  4.600e+00  1.630e+01  4.730e+01  6.280e+01  5.510e+01
  2.570e+01  2.860e+01  4.470e+01  3.680e+01  3.760e+01  1.450e+01
  2.110e+01  2.710e+01  1.240e+01  2.730e+01  5.110e+01  6.090e+01
  3.600e+01  6.260e+01  7.660e+01  5.780e+01  2.750e+01  3.620e+01
  3.750e+01  3.920e+01  3.390e+01  2.020e+01  2.560e+01  1.890e+01
  3.330e+01  2.660e+01  3.610e+01  3.180e+01  3.720e+01  3.130e+01
  4.570e+01  5.020e+01  5.850e+01  3.360e+01  7.510e+01  8.050e+01
  7.990e+01  4.380e+01  4.310e+01  5.760e+01  5.680e+01  6.040e+01
  5.050e+01  8.140e+01  7.860e+01  7.520e+01  6.430e+01  7.350e+01
  8.380e+01  7.410e+01  7.770e+01  7.250e+01  8.070e+01  8.770e+01
  9.010e+01  8.530e+01  5.990e+01  7.790e+01  7.920e+01  9.450e+01
  7.530e+01  7.280e+01  7.680e+01  7.830e+01  9.130e+01  9.500e+01
  9.610e+01  9.530e+01  9.940e+01  8.920e+01  8.330e+01  8.030e+01
  9.150e+01  9.220e+01  9.310e+01  8.620e+01  8.510e+01  7.870e+01
  8.830e+01  9.040e+01  8.650e+01  8.150e+01  7.850e+01  9.390e+01
  9.490e+01  9.460e+01  8.640e+01  8.820e+01  9.200e+01  9.480e+01
  9.700e+01  8.660e+01  6.710e+01  6.730e+01  8.500e+01  8.250e+01
  8.120e+01  9.000e+01  6.690e+01  6.770e+01  7.160e+01  6.250e+01
  6.300e+01  6.760e+01  8.610e+01  8.260e+01  5.300e+01  6.350e+01
  5.120e+01  4.600e+01  5.480e+01  5.660e+01  4.210e+01  4.550e+01
  4.480e+01  4.560e+01  4.410e+01  4.180e+01  6.170e+01  5.140e+01
  3.970e+01  2.780e+01  3.770e+01  3.060e+01  3.280e+01  2.790e+01
  4.860e+01  2.420e+01  4.050e+01  4.320e+01  5.240e+01  5.070e+01
  1.570e+01  3.050e+01  5.040e+01  2.900e+01  2.590e+01  2.480e+01
  2.610e+01  2.460e+01  3.640e+01  4.460e+01  5.090e+01  4.510e+01
  3.710e+01  2.910e+01  3.320e+01  4.280e+01  4.030e+01  3.550e+01
  3.830e+01  3.260e+01  4.100e+01  4.340e+01  1.330e+01  2.210e+01
  2.360e+01  3.120e+01  5.900e+00  4.720e+01  1.480e+01  2.240e+01
  3.420e+01  2.700e+00  1.000e-01  1.860e+01  3.160e+01  2.630e+01
  2.160e+01  2.720e+01  3.000e+01  4.090e+01  2.340e+01  2.670e+01
  5.350e+01  3.400e+01  1.420e+01  5.800e+00  9.900e+00  2.580e+01
  4.130e+01  4.290e+01  6.640e+01  3.860e+01  3.630e+01  4.490e+01
  5.550e+01  4.230e+01  6.000e+01  5.650e+01  5.360e+01  6.720e+01
  5.170e+01  6.160e+01  7.630e+01  7.050e+01  7.320e+01  5.960e+01
  7.600e+01  7.020e+01  7.120e+01  8.000e+01  8.200e+01  9.350e+01
  8.790e+01  7.700e+01  9.050e+01  9.550e+01  1.001e+02  9.850e+01
  7.560e+01  8.390e+01  7.910e+01  8.280e+01  8.600e+01  7.930e+01
  8.960e+01  8.740e+01  9.110e+01  7.500e+01  7.750e+01  8.080e+01
  8.710e+01  8.480e+01  8.940e+01  6.800e+01  6.130e+01  6.670e+01
  4.520e+01  5.490e+01  6.370e+01  7.170e+01  5.630e+01  5.540e+01
  6.180e+01  4.390e+01  4.170e+01  5.370e+01  4.160e+01  3.940e+01
  5.210e+01  3.290e+01  3.700e+01  4.370e+01  3.380e+01  2.700e+01
  3.520e+01  1.870e+01  3.370e+01  1.550e+01  4.680e+01  3.930e+01
  4.840e+01  6.190e+01  5.720e+01  5.730e+01  3.170e+01  4.430e+01
  4.960e+01  2.620e+01  5.430e+01  2.850e+01  1.740e+01  1.980e+01
  3.240e+01  4.000e+01  5.320e+01  4.120e+01  2.680e+01  3.220e+01
  3.070e+01  1.560e+01  4.740e+01  5.010e+01  2.150e+01  1.780e+01
  2.100e+01  6.570e+01  4.610e+01  4.830e+01  6.910e+01  5.750e+01
  5.620e+01  5.610e+01  5.250e+01  4.260e+01  4.200e+01  5.830e+01
  6.930e+01  6.230e+01  5.060e+01  6.970e+01  6.900e+01  8.490e+01
  9.290e+01  9.030e+01  9.230e+01  9.470e+01  9.300e+01  9.380e+01
  9.420e+01  8.840e+01  8.890e+01  8.690e+01  9.020e+01  9.690e+01
  8.270e+01  8.970e+01  8.870e+01  9.180e+01  8.110e+01  8.540e+01
  8.860e+01  6.700e+01  6.240e+01  5.840e+01  7.290e+01  5.330e+01
  6.030e+01  5.530e+01  7.100e+01  2.830e+01  4.780e+01  2.430e+01
  3.090e+01  3.150e+01  5.080e+01  1.220e+01  1.620e+01  5.340e+01
  3.500e+01  3.140e+01  3.820e+01  4.240e+01  2.740e+01  2.400e+01
  2.810e+01  2.690e+01  1.490e+01  1.520e+01  2.990e+01  2.390e+01
  2.510e+01  2.970e+01  2.170e+01  3.010e+01  2.410e+01  1.360e+01
  2.890e+01  6.210e+01  3.880e+01  6.460e+01  5.980e+01  6.480e+01
  5.520e+01  6.380e+01  7.200e+01  5.310e+01  4.020e+01  6.490e+01
  6.920e+01  6.290e+01  5.740e+01  6.960e+01  8.630e+01  9.280e+01
  9.630e+01  9.070e+01  9.270e+01  8.550e+01  9.890e+01  9.250e+01
  9.360e+01  7.380e+01  8.060e+01  6.840e+01  4.640e+01  4.760e+01
  3.810e+01  3.780e+01  4.420e+01  2.800e+01  5.260e+01  2.010e+01
  2.440e+01  1.030e+01  1.470e+01  1.510e+01  3.960e+01  1.530e+01
  1.930e+01  2.060e+01  3.890e+01  1.500e+01  1.880e+01  1.440e+01
  2.330e+01  6.600e+00  4.150e+01  3.210e+01  1.760e+01  5.870e+01
  2.220e+01  6.050e+01  4.580e+01  2.250e+01  4.940e+01  6.820e+01
  6.630e+01  5.910e+01  8.020e+01  7.590e+01  1.006e+02  9.090e+01
  8.040e+01  8.990e+01  5.920e+01  6.220e+01  5.940e+01  6.600e+01
  6.780e+01  3.450e+01  1.920e+01  5.410e+01  3.190e+01  4.700e+01
  2.760e+01 -4.200e+00  1.100e+01  1.800e+01  1.790e+01  2.950e+01
  4.650e+01  3.460e+01  4.820e+01  6.610e+01  8.520e+01  7.180e+01
  9.320e+01  9.410e+01  9.370e+01  9.210e+01  7.620e+01  7.240e+01
  5.640e+01  5.270e+01  4.950e+01  4.590e+01  4.060e+01  4.670e+01
  4.070e+01  5.460e+01  3.990e+01  1.770e+01  1.970e+01  2.490e+01
  4.450e+01  5.800e+01  5.000e+01  3.510e+01  5.790e+01  7.230e+01]
feelslikemin: [ 29.   33.2  37.7   8.    7.   -2.8  -4.2  -9.1  -5.8  15.1  34.1  30.8
  21.9  21.   19.5  25.7  34.8  31.3  30.9  29.9  40.   45.8  27.2  28.8
  22.5  18.1  14.5  18.6  12.8  12.7  24.5  17.7   9.    3.   19.3  22.8
  40.1  21.5   2.2  26.9  24.2  15.6  20.   15.7  12.3  16.2  39.6  40.9
  36.2  43.1  52.9  53.6  56.4  17.2  15.3  25.8  33.4  35.4  18.7  11.9
   9.5  32.9  34.7  30.5  30.7  10.2   2.    7.3   8.2   2.3  -0.8  10.5
  13.6  26.6  30.4  41.5  16.4  13.   31.9  62.   52.4  52.2  43.   40.2
  38.9  44.6  54.3  28.2  22.2  23.8  31.4  57.4  57.5  44.2  46.4  51.5
  62.8  45.5  56.7  58.2  51.6  39.1  36.   43.8  45.3  52.   58.   50.
  54.2  58.4  60.4  42.4  39.9  44.5  33.8  34.6  34.9  46.8  47.3  47.
  50.1  38.5  64.3  68.4  64.   59.2  57.8  48.6  57.7  55.4  56.8  55.7
  57.   60.2  61.5  56.3  54.1  54.5  59.9  53.9  51.8  51.2  54.   63.1
  66.2  69.1  67.   68.6  62.9  70.3  58.9  62.3  64.4  67.9  65.6  61.2
  55.3  54.7  49.2  59.7  66.1  73.   67.5  65.1  67.7  56.2  65.   71.3
  65.8  61.8  66.7  69.7  70.9  70.4  72.   68.1  59.3  64.7  64.9  55.9
  60.1  63.6  65.7  65.4  66.4  59.5  61.   60.8  60.5  64.6  62.4  64.8
  63.2  53.3  57.1  60.9  60.6  59.1  53.8  61.4  55.1  46.6  47.7  55.2
  57.2  61.6  63.5  62.1  62.2  61.7  62.6  67.4  56.1  47.8  41.4  41.7
  46.9  53.1  63.8  63.3  66.8  68.   65.3  56.6  43.2  31.7  38.   50.8
  42.7  50.4  41.3  36.3  32.7  27.8  29.5  46.7  33.   52.3  35.5  31.2
  26.2  28.6  11.8   7.8  25.   30.1  25.5  22.   17.6  27.9  23.   18.2

## OverDoseDataPA1

In [2]:
overdose_PA_df = pd.read_excel('../data/raw/OverdoseDataPA1.xlsx', engine='calamine')
overdose_PA_df.head(5)

,dose_count,incident_id,incident_time,day,incident_county_name,incident_state,victim_id,gender_desc,age_range,race,...,geocoded_column,geocoded_column_address,geocoded_column_city,geocoded_column_zip,geocoded_column_1_city,geocoded_column_1_zip,geocoded_column_1_state,geocoded_column_1,dose_unit,geocoded_column_1_address
0,1,184,13:52:00,Wednesday,Allegheny,Pennsylvania,124,Female,20 - 24,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
1,2,39237,4:13:00,Saturday,Allegheny,Pennsylvania,31680,Female,50 - 59,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
2,1,27008,0:15:00,Monday,Lackawanna,Pennsylvania,21028,Female,30 - 39,BLACK,...,POINT (-75.612183 41.439101),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-75.032709 41.332572),0,NaN
3,2,47495,21:00:00,Saturday,Adams,Pennsylvania,38590,Male,40 - 49,WHITE,...,POINT (-77.222243 39.872096),NaN,NaN,NaN,NaN,NaN,NaN,POINT (0 0),2,NaN
4,1,25677,17:30:00,Wednesday,Allegheny,Pennsylvania,20086,Male,50 - 59,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN

In [3]:
overdose_PA_df

,dose_count,incident_id,incident_time,day,incident_county_name,incident_state,victim_id,gender_desc,age_range,race,...,geocoded_column,geocoded_column_address,geocoded_column_city,geocoded_column_zip,geocoded_column_1_city,geocoded_column_1_zip,geocoded_column_1_state,geocoded_column_1,dose_unit,geocoded_column_1_address
0,1,184,13:52:00,Wednesday,Allegheny,Pennsylvania,124,Female,20 - 24,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
1,2,39237,4:13:00,Saturday,Allegheny,Pennsylvania,31680,Female,50 - 59,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
2,1,27008,0:15:00,Monday,Lackawanna,Pennsylvania,21028,Female,30 - 39,BLACK,...,POINT (-75.612183 41.439101),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-75.032709 41.332572),0,NaN
3,2,47495,21:00:00,Saturday,Adams,Pennsylvania,38590,Male,40 - 49,WHITE,...,POINT (-77.222243 39.872096),NaN,NaN,NaN,NaN,NaN,NaN,POINT (0 0),2,NaN
4,1,25677,17:30:00,Wednesday,Allegheny,Pennsylvania,20086,Male,50 - 59,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53932,2,39326,14:27:00,Tuesday,Cambria,Pennsylvania,31751,Male,40 - 49,BLACK,...,POINT (-78.718942 40.491275),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-78.718942 40.491275),2,NaN
53933,2,14560,16:36:00,Friday,York,Pennsylvania,11654,Male,25 - 29,WHITE,...,POINT (-76.725761 39.921925),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-76.725761 39.921925),4,NaN
53934,1,12293,21:30:00,Monday,Allegheny,Pennsylvania,9750,Female,30 - 39,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
53935,2,35341,21:58:00,Sunday,Westmoreland,Pennsylvania,28171,Male,40 - 49,WHITE,...,POINT (-79.471341 40.310315),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.471341 40.310315),2,NaN
53936,0,25135,22:00:00,Friday,Fayette,Pennsylvania,19712,Male,40 - 49,WHITE,...,POINT (-79.651896 39.919448),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.651896 39.919448),0,NaN

In [90]:
overdose_PA_df.columns

Index(['dose_count', 'incident_id', 'incident_time', 'day',
       'incident_county_name', 'incident_state', 'victim_id', 'gender_desc',
       'age_range', 'race', 'ethnicity_desc', 'victim_state', 'victim_county',
       'accidental_exposure', 'victim_od_drug_id', 'susp_od_drug_desc',
       'naloxone_administered', 'administration_id', 'incident_date',
       'dose_desc', 'response_time_desc', 'survive', 'response_desc',
       'revive_action_desc', 'third_party_admin_desc',
       'incident_county_fips_code', 'incident_county_lat',
       'incident_county_long', 'victim_county_fips_code', 'victim_county_lat',
       'victim_county_long', 'geocoded_column_state', 'geocoded_column',
       'geocoded_column_address', 'geocoded_column_city',
       'geocoded_column_zip', 'geocoded_column_1_city',
       'geocoded_column_1_zip', 'geocoded_column_1_state', 'geocoded_column_1',
       'dose_unit', 'geocoded_column_1_address'],
      dtype='object')

In [94]:
overdose_sel_cols = ['incident_time','day','incident_county_name','gender_desc','age_range',
                     'race','ethnicity_desc','accidental_exposure','susp_od_drug_desc',
                     'naloxone_administered','incident_date','response_time_desc','survive',
                     'incident_county_lat','incident_county_long']

In [95]:
overdose_PA_df[overdose_sel_cols].describe()

       incident_county_lat  incident_county_long
count         53937.000000          53937.000000
mean             40.551382            -77.434264
std               0.566338              1.892110
min              39.854804            -80.351074
25%              40.167598            -79.762866
50%              40.419746            -76.725761
75%              40.815095            -75.711070
max              41.994138            -75.032709

In [91]:
overdose_PA_df['day'].value_counts()

day
Saturday     8724
Friday       8474
Thursday     7670
Wednesday    7453
Tuesday      7402
Sunday       7262
Monday       6952
Name: count, dtype: int64

In [15]:
overdose_PA_df['incident_county_name'].count()

53937

In [20]:
down_sel = overdose_PA_df[overdose_PA_df['incident_county_name'] == 'Allegheny']
down_sel

,dose_count,incident_id,incident_time,day,incident_county_name,incident_state,victim_id,gender_desc,age_range,race,...,geocoded_column,geocoded_column_address,geocoded_column_city,geocoded_column_zip,geocoded_column_1_city,geocoded_column_1_zip,geocoded_column_1_state,geocoded_column_1,dose_unit,geocoded_column_1_address
0,1,184,13:52:00,Wednesday,Allegheny,Pennsylvania,124,Female,20 - 24,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
1,2,39237,4:13:00,Saturday,Allegheny,Pennsylvania,31680,Female,50 - 59,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
4,1,25677,17:30:00,Wednesday,Allegheny,Pennsylvania,20086,Male,50 - 59,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
6,1,3984,0:02:00,Friday,Allegheny,Pennsylvania,3252,Male,50 - 59,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
22,0,42561,8:00:00,Monday,Allegheny,Pennsylvania,34747,Male,40 - 49,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53897,2,26867,0:00:00,Saturday,Allegheny,Pennsylvania,20932,Female,20 - 24,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (0 0),4,NaN
53904,2,39762,23:00:00,Monday,Allegheny,Pennsylvania,32155,Male,30 - 39,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),4,NaN
53918,0,23593,1:00:00,Saturday,Allegheny,Pennsylvania,18642,Male,25 - 29,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
53929,1,39064,21:16:00,Sunday,Allegheny,Pennsylvania,31523,Male,40 - 49,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),4,NaN
53934,1,12293,21:30:00,Monday,Allegheny,Pennsylvania,9750,Female,30 - 39,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN

In [21]:
down_sel['susp_od_drug_desc'].unique()

array(['HEROIN', 'FENTANYL', 'PHARMACEUTICAL OTHER', 'UNKNOWN',
       'MARIJUANA', 'CARFENTANIL',
       'FENTANYL ANALOG/OTHER SYNTHETIC OPIOID', 'METHADONE', 'ALCOHOL',
       'OTHER', 'BENZODIAZEPINES (I.E.VALIUM, XANAX, ATIVAN, ETC)',
       'COCAINE/CRACK', 'PHARMACEUTICAL OPIOID', 'METHAMPHETAMINE',
       'SYNTHETIC MARIJUANA', 'PHARMACEUTICAL STIMULANT',
       'BARBITURATES (I.E. AMYTAL, NEMBUTAL, ETC)',
       'BUPRENORPHINE (I.E. SUBOXONE, SUBLOCADE, SUBUTEX, BUTRANS, BUPRENEX, ETC)',
       'XYLAZINE', 'BATH SALTS'], dtype=object)

In [48]:
susp_drugs = ['HEROIN', 'FENTANYL', 'CARFENTANIL',
       'FENTANYL ANALOG/OTHER SYNTHETIC OPIOID', 'METHADONE',
       'PHARMACEUTICAL OPIOID',
       'BUPRENORPHINE (I.E. SUBOXONE, SUBLOCADE, SUBUTEX, BUTRANS, BUPRENEX, ETC)']

In [49]:
down_sel2 = down_sel[down_sel['susp_od_drug_desc'].isin(susp_drugs)].copy()

In [50]:
down_sel2

,dose_count,incident_id,incident_time,day,incident_county_name,incident_state,victim_id,gender_desc,age_range,race,...,geocoded_column,geocoded_column_address,geocoded_column_city,geocoded_column_zip,geocoded_column_1_city,geocoded_column_1_zip,geocoded_column_1_state,geocoded_column_1,dose_unit,geocoded_column_1_address
0,1,184,13:52:00,Wednesday,Allegheny,Pennsylvania,124,Female,20 - 24,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
1,2,39237,4:13:00,Saturday,Allegheny,Pennsylvania,31680,Female,50 - 59,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
4,1,25677,17:30:00,Wednesday,Allegheny,Pennsylvania,20086,Male,50 - 59,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
6,1,3984,0:02:00,Friday,Allegheny,Pennsylvania,3252,Male,50 - 59,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
22,0,42561,8:00:00,Monday,Allegheny,Pennsylvania,34747,Male,40 - 49,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53879,0,40768,17:08:00,Tuesday,Allegheny,Pennsylvania,33077,Male,30 - 39,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.917118 40.910832),0,NaN
53891,2,37405,16:00:00,Friday,Allegheny,Pennsylvania,30037,Male,30 - 39,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),4,NaN
53904,2,39762,23:00:00,Monday,Allegheny,Pennsylvania,32155,Male,30 - 39,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),4,NaN
53929,1,39064,21:16:00,Sunday,Allegheny,Pennsylvania,31523,Male,40 - 49,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),4,NaN
53934,1,12293,21:30:00,Monday,Allegheny,Pennsylvania,9750,Female,30 - 39,WHITE,...,POINT (-79.986198 40.467355),NaN,NaN,NaN,NaN,NaN,NaN,POINT (-79.986198 40.467355),0,NaN

In [66]:
# Use this cell for dataset information.  Just change the column name
down_sel2['naloxone_administered'].value_counts()

naloxone_administered
Y    4115
N    1198
Name: count, dtype: int64

In [92]:
print(down_sel2['incident_county_name'].unique())
# print(down_sel2['incident_time'].unique())
print(down_sel2['day'].unique())
print(down_sel2['gender_desc'].unique())
print(down_sel2['age_range'].unique())
print(down_sel2['ethnicity_desc'].unique())
print(down_sel2['accidental_exposure'].unique())
print(down_sel2['susp_od_drug_desc'].unique())
print(down_sel2['incident_date'].unique())
print(down_sel2['response_time_desc'].unique())
print(down_sel2['survive'].unique())
print(down_sel2['incident_county_lat'].unique())
print(down_sel2['incident_county_long'].unique())
print(down_sel2['naloxone_administered'].unique())

['Allegheny']
['Wednesday' 'Saturday' 'Friday' 'Monday' 'Sunday' 'Thursday' 'Tuesday']
['Female', 'Male', 'Unknown']
Categories (3, object): ['Female', 'Male', 'Unknown']
['20 - 24' '50 - 59' '40 - 49' '30 - 39' '25 - 29' '70 - 79' '15 - 19'
 '60 - 69' '0 - 9' '14-Oct' '80 - *']
['Unknown' 'NON-HISPANIC OR NOT LATINO' 'HISPANIC or LATINO']
['N' 'Y']
['HEROIN' 'FENTANYL' 'CARFENTANIL'
 'FENTANYL ANALOG/OTHER SYNTHETIC OPIOID' 'METHADONE'
 'PHARMACEUTICAL OPIOID'
 'BUPRENORPHINE (I.E. SUBOXONE, SUBLOCADE, SUBUTEX, BUTRANS, BUPRENEX, ETC)']
['3/7/2018' '4/22/2023' '5/26/2021' ... '12/20/2019' '11/9/2019'
 '12/23/2022']
[nan '1-3 MINUTES' '<1 MINUTE' 'DID NOT WORK' '>5 MINUTES' '3-5 MINUTES'
 "DON'T KNOW"]
['N' 'U' 'Y']
[40.467355]
[-79.986198]
['Y' 'N']

In [74]:
down_sel2.dtypes

dose_count                      int64
incident_id                     int64
incident_time                  object
day                            object
incident_county_name           object
incident_state                 object
victim_id                       int64
gender_desc                  category
age_range                      object
race                           object
ethnicity_desc                 object
victim_state                   object
victim_county                  object
accidental_exposure            object
victim_od_drug_id               int64
susp_od_drug_desc              object
naloxone_administered          object
administration_id               int64
incident_date                  object
dose_desc                      object
response_time_desc             object
survive                        object
response_desc                  object
revive_action_desc             object
third_party_admin_desc         object
incident_county_fips_code       int64
incident_county_lat           float64
incident_county_long          float64
victim_county_fips_code       float64
victim_county_lat             float64
victim_county_long            float64
geocoded_column_state         float64
geocoded_column                object
geocoded_column_address       float64
geocoded_column_city          float64
geocoded_column_zip           float64
geocoded_column_1_city        float64
geocoded_column_1_zip         float64
geocoded_column_1_state       float64
geocoded_column_1              object
dose_unit                       int64
geocoded_column_1_address     float64
dtype: object

In [77]:
type(down_sel2['incident_date'][0])

str

In [70]:
down_sel2['incident_time'][0]

'13:52:00'

In [72]:
down_sel2['gender_desc'] = down_sel2['gender_desc'].astype('category')

In [73]:
type(down_sel2['gender_desc'][0])

str

In [110]:
down_sel2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5313 entries, 0 to 53934
Data columns (total 42 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   dose_count                 5313 non-null   int64
 1   incident_id                5313 non-null   int64
 2   incident_time              5313 non-null   object
 3   day                        5313 non-null   object
 4   incident_county_name       5313 non-null   object
 5   incident_state             5313 non-null   object
 6   victim_id                  5313 non-null   int64
 7   gender_desc                5313 non-null   category
 8   age_range                  5313 non-null   object
 9   race                       5313 non-null   object
 10  ethnicity_desc             5313 non-null   object
 11  victim_state               4921 non-null   object
 12  victim_county              4921 non-null   object
 13  accidental_exposure        5313 non-null   object
 14  victim_od_drug_id          5313 non-null   int64
 15  susp_od_drug_desc          5313 non-null   object
 16  naloxone_administered      5313 non-null   object
 17  administration_id          5313 non-null   int64
 18  incident_date              5313 non-null   object
 19  dose_desc                  4115 non-null   object
 20  response_time_desc         3835 non-null   object
 21  survive                    5313 non-null   object
 22  response_desc              4118 non-null   object
 23  revive_action_desc         3835 non-null   object
 24  third_party_admin_desc     2116 non-null   object
 25  incident_county_fips_code  5313 non-null   int64
 26  incident_county_lat        5313 non-null   float64
 27  incident_county_long       5313 non-null   float64
 28  victim_county_fips_code    4921 non-null   float64
 29  victim_county_lat          5313 non-null   float64
 30  victim_county_long         5313 non-null   float64
 31  geocoded_column_state      0 non-null      float64
 32  geocoded_column            5313 non-null   object
 33  geocoded_column_address    0 non-null      float64
 34  geocoded_column_city       0 non-null      float64
 35  geocoded_column_zip        0 non-null      float64
 36  geocoded_column_1_city     0 non-null      float64
 37  geocoded_column_1_zip      0 non-null      float64
 38  geocoded_column_1_state    0 non-null      float64
 39  geocoded_column_1          5313 non-null   object
 40  dose_unit                  5313 non-null   int64
 41  geocoded_column_1_address  0 non-null      float64
dtypes: category(1), float64(13), int64(7), object(21)
memory usage: 1.8+ MB